services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsiu-app
    container_name: whatsiu-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/var/www
    networks:
      - whatsiu-network

  nginx:
    image: nginx:alpine
    container_name: whatsiu-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - whatsiu-network

networks:
  whatsiu-network:
    driver: bridge
