[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "php84Extensions.pdo_pgsql", "php84Extensions.mbstring", "php84Extensions.bcmath", "php84Extensions.gd", "php84Extensions.fileinfo", "php84Extensions.tokenizer", "php84Extensions.xml", "nodejs_20", "nginx", "libmysqlclient"]

[phases.build]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev",
    "npm install",
    "npm run build",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "chmod -R 777 storage bootstrap/cache && php artisan migrate --force && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
